sudo: required
services:
  - docker

before_install:
  - docker build -t hosseinghayebi/docker-react -f Dockerfile.dev  .

scripts:
  - docker run hosseinghayebi/docker-react npm run test -- --coverage
